# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: abeprototest.proto
# Protobuf Python Version: 6.32.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    32,
    1,
    '',
    'abeprototest.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x12\x61\x62\x65prototest.proto\"m\n\roabe_numattrs\x12,\n\x07\x61ttrmap\x18\x01 \x03(\x0b\x32\x1b.oabe_numattrs.AttrmapEntry\x1a.\n\x0c\x41ttrmapEntry\x12\x0b\n\x03key\x18\x01 \x01(\x05\x12\r\n\x05value\x18\x02 \x01(\x0c:\x02\x38\x01\"\xc7\x01\n\x0foabe_ciphertext\x12*\n\x05\x61ttrs\x18\x01 \x03(\x0b\x32\x1b.oabe_ciphertext.AttrsEntry\x12\r\n\x05\x63iph1\x18\x02 \x01(\x0c\x12\r\n\x05\x63iph2\x18\x03 \x01(\x0c\x12\n\n\x02IV\x18\x04 \x01(\x0c\x12\x0f\n\x07\x61uthtag\x18\x05 \x01(\x0c\x12\x0f\n\x07\x61\x65sciph\x18\x06 \x01(\x0c\x1a<\n\nAttrsEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\x1d\n\x05value\x18\x02 \x01(\x0b\x32\x0e.oabe_numattrs:\x02\x38\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'abeprototest_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_OABE_NUMATTRS_ATTRMAPENTRY']._loaded_options = None
  _globals['_OABE_NUMATTRS_ATTRMAPENTRY']._serialized_options = b'8\001'
  _globals['_OABE_CIPHERTEXT_ATTRSENTRY']._loaded_options = None
  _globals['_OABE_CIPHERTEXT_ATTRSENTRY']._serialized_options = b'8\001'
  _globals['_OABE_NUMATTRS']._serialized_start=22
  _globals['_OABE_NUMATTRS']._serialized_end=131
  _globals['_OABE_NUMATTRS_ATTRMAPENTRY']._serialized_start=85
  _globals['_OABE_NUMATTRS_ATTRMAPENTRY']._serialized_end=131
  _globals['_OABE_CIPHERTEXT']._serialized_start=134
  _globals['_OABE_CIPHERTEXT']._serialized_end=333
  _globals['_OABE_CIPHERTEXT_ATTRSENTRY']._serialized_start=273
  _globals['_OABE_CIPHERTEXT_ATTRSENTRY']._serialized_end=333
# @@protoc_insertion_point(module_scope)
